version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
